#ifndef H7FOC_COMM_COMM_TYPES_H
#define H7FOC_COMM_COMM_TYPES_H

#include <stdint.h>

typedef enum
{
    COMM_OK = 0,
    COMM_ERROR = -1,
    COMM_UNSUPPORTED = -2,
} comm_status_t;

typedef enum
{
    COMM_MODBUS_REG_STATUS_MOVE_DONE = 0x0001,

    COMM_MODBUS_REG_INPUT_AXIS0_POS = 0x0101,
    COMM_MODBUS_REG_INPUT_AXIS0_SPEED = 0x0103,
    COMM_MODBUS_REG_INPUT_AXIS0_CURRENT = 0x0105,

    COMM_MODBUS_REG_CMD_LED = 0x0201,
    COMM_MODBUS_REG_CMD_AXIS0_ENABLE = 0x0202,
    COMM_MODBUS_REG_CMD_AXIS0_MOVE = 0x0203,

    COMM_MODBUS_REG_HOLD_AXIS0_TARGET_POS = 0x0301,
    COMM_MODBUS_REG_HOLD_AXIS0_TARGET_SPEED = 0x0303,
    COMM_MODBUS_REG_HOLD_SPEED_KP = 0x0311,
    COMM_MODBUS_REG_HOLD_SPEED_KI = 0x0313,
    COMM_MODBUS_REG_HOLD_POS_KP = 0x0315,
    COMM_MODBUS_REG_HOLD_POS_KI = 0x0317,
    COMM_MODBUS_REG_HOLD_IQ_KP = 0x0319,
    COMM_MODBUS_REG_HOLD_IQ_KI = 0x031B,
    COMM_MODBUS_REG_HOLD_ID_KP = 0x031D,
    COMM_MODBUS_REG_HOLD_ID_KI = 0x031F,
    COMM_MODBUS_REG_HOLD_CTRL_MODE = 0x0321,
    COMM_MODBUS_REG_HOLD_MOVE_FLAG = 0x0322,
    COMM_MODBUS_REG_HOLD_IQ_REF = 0x0323,
} comm_modbus_reg_t;

#endif
